# Generated by Django 3.2.23 on 2024-02-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_userchoices_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoices',
            name='userphoto',
            field=models.ImageField(default='', upload_to='app1/images'),
        ),
    ]
